name: Deploy Blood Bank System to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1 # CHANGE this to your desired AWS Region (e.g., eu-central-1)
      S3_DASHBOARD_BUCKET: blood-bank-dashboard # REPLACE with your S3 bucket name

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          # Install AWS SAM CLI and Boto3 (required for some operations)
          pip install aws-sam-cli boto3

      - name: Configure AWS Credentials
        # This action uses the secrets stored in GitHub to authorize with AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SAM Build
        run: sam build --template template.yaml

      - name: SAM Deploy (Backend)
        id: sam_deploy
        run: |
          sam deploy \
            --template-file .aws-sam/build/template.yaml \
            --stack-name BloodBankStack \
            --region ${{ env.AWS_REGION }} \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset
            --confirm-changeset \
            --no-fail-on-empty-changeset \
            --resolve-s3 # Ensures SAM can upload code artifacts

      - name: Get API Endpoint URL
        id: get_api_url
        # Uses AWS CLI to retrieve the API URL from the deployed stack's outputs
        run: |
          API_URL=$(aws cloudformation describe-stacks --stack-name BloodBankStack --query 'Stacks[0].Outputs[?OutputKey==`ApiUrl`].OutputValue' --output text)
          echo "Retrieved API URL: $API_URL"
          echo "API_URL=$API_URL" >> $GITHUB_OUTPUT # Set as output variable for next step

      - name: Inject API URL into Frontend Script
        # This uses the retrieved API_URL to update the script.js file directly
        run: |
          API_BASE_URL="${{ steps.get_api_url.outputs.API_URL }}"
          echo "Updating script.js with base URL: $API_BASE_URL"
          
          # Use sed to replace the placeholder lines with the actual generated URL
          # Assumes the script.js has the line: const BASE_API_URL = 'https://PLACEHOLDER_URL_HERE/dev/';
          sed -i "s|// const BASE_API_URL = 'https://PLACEHOLDER_URL_HERE/dev/';|const BASE_API_URL = '$API_BASE_URL';|" frontend/script.js
          
          # Clean up any potential double quotes or trailing slashes if necessary
          sed -i "s|'\"|'|g" frontend/script.js

      - name: Deploy Frontend to S3 (Static Hosting)
        # Syncs the updated script.js and all other frontend files to the S3 bucket
        run: |
          aws s3 sync ./frontend/ s3://${{ env.S3_DASHBOARD_BUCKET }}/ --delete
          # Sets Cache-Control headers for index.html to ensure users get the latest script.js reference
          aws s3 cp s3://${{ env.S3_DASHBOARD_BUCKET }}/index.html s3://${{ env.S3_DASHBOARD_BUCKET }}/index.html --metadata-directive REPLACE --cache-control max-age=0 --content-type text/html
